###########
# BUILDER #
###########

FROM python:3.8.7-slim-buster as builder

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential \
  && apt-get clean

WORKDIR /usr/src/app

# create venv
RUN python -m venv /opt/venv
# activate it
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && pip install pip-tools
COPY ./pre-reqs.in .
COPY ./requirements.in .
RUN pip-compile pre-reqs.in > pre-reqs.txt
RUN pip-compile requirements.in > requirements.txt
RUN pip-sync pre-reqs.txt requirements.txt
RUN pip install -r pre-reqs.txt
RUN pip install -r requirements.txt

#########
# FINAL #
#########

# pull official base image
FROM python:3.8.7-slim-buster

RUN apt-get update \
  && apt-get install -y --no-install-recommends postgresql netcat curl \
  && apt-get clean

## set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

COPY --from=builder /opt/venv /opt/venv

# activate the venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip
RUN pip install "uvicorn[standard]==0.13.1" "gunicorn==20.0.4"

WORKDIR /usr/src/app

COPY . .

COPY ./start.sh .
RUN chmod +x /usr/src/app/start.sh

CMD ["/usr/src/app/start.sh"]
